
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami  # URL du repo Helm Bitnami
    targetRevision: 23.0.11  # Version du chart Helm que vous souhaitez déployer
    chart: wordpress  # Le nom du chart Helm dans le repo
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress  # Namespace où WordPress sera déployé
  syncPolicy:
    automated:
      prune: true
      selfHeal: true