apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GuillaumeLangevin2212/argocd-test.git
    targetRevision: HEAD
    path: config_app/wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: wordpress-de-fou
# spec:
#   destination:
#     namespace: wordpress
#     server: https://kubernetes.default.svc
#   source:
#     path: ''
#     repoURL: https://charts.bitnami.com/bitnami
#     targetRevision: 24.1.17
#     chart: wordpress
#   sources: []
#   project: default
