apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mon-repo/mon-application.git  # URL de ton dépôt Git
    targetRevision: HEAD
    path: wordpress-app  # chemin relatif dans ton dépôt Git où se trouve ton Chart.yaml
    helm:
      valueFiles:
        - values.yaml  # Fichier de valeurs Helm pour personnaliser le chart
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress  # Namespace où WordPress sera déployé
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
